### ISSUE TITLE
minor inconsistency

### ISSUE THREAD

**Issue by CaninoDev** [learn-co-curriculum/tweet-shortener#11]
under the following:
```
"hello" becomes 'hi'
"to, two, too" become '2' 
"for, four" become '4'
'be' becomes 'b'
'you' becomes 'u'
"at" becomes "@" 
"and" becomes "&"
```
the use of single quotes and double quotes are mixed (unless this was intentional as I noticed the first five entries used non-special characters for substitution.)

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
