### ISSUE TITLE
inconsistencies between description and tests

### ISSUE THREAD

**Issue by JohnathanCh** [learn-co-curriculum/tweet-shortener#12]
From the description:

"Write a new method, selective_tweet_shortener, that only does the substitutions if the tweet is longer than 140 characters. If the tweet is 140 characters or shorter, just return the original tweet."

From the Rspec:

`# Question 3
  describe '#selective_tweet_shortener' do
    it "shortens tweets that are more than 140 characters" do
      tweet_one_length = tweet_one.length
      tweet_three_length = tweet_three.length
      tweet_five_length = tweet_five.length
      expect(selective_tweet_shortener(tweet_one).length).to be < tweet_one_length
      expect(selective_tweet_shortener(tweet_three).length).to be < tweet_three_length
      expect(selective_tweet_shortener(tweet_five).length).to be < tweet_five_length
    end

    it "does not shorten tweets that are less than 130 characters" do
      expect(selective_tweet_shortener(tweet_two).length).to be == tweet_two.length
      expect(selective_tweet_shortener(tweet_four).length).to be == tweet_four.length
    end

  end
`

I wasn't sure if this discrepancy was meant to "keep us on our toes" or if it was accidental.

**Comment by nmala** [comment]
I noticed the same and thought to check out if anyone else came across this...guess I'm not alone! I agree, the instruction wording is a bit off. I had to set my index range to [0..135] to account for the ellipsis and the space before it. Unless, as you stated, it's just to keep us on our toes...

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
