### ISSUE TITLE
Learn Submit, Learn, and learn.co acting up for me in this lab

### ISSUE THREAD

**Issue by rhoprhh** [learn-co-curriculum/tweet-shortener#7]
![screen shot 2016-03-24 at 2 13 35 pm](https://cloud.githubusercontent.com/assets/17771614/14026885/56fde65c-f1cb-11e5-9a35-5ba6c794b682.png)

```
[14:03:51] (master) tweet-shortener-001-prework-web
// ♥ pwd
/Users/rhopkins/Development/code/tweet-shortener-001-prework-web
[14:04:33] (master) tweet-shortener-001-prework-web
// ♥ learn submit
It doesn't look like you're in a lesson directory.
Please cd into an appropriate directory and try again.
```

I am having several problems with learn on this lab.
The screenshot is showing it passing locally, but I cannot for the life of me get it to pass online.
Both typing learn in the terminal and clicking test in the app window got the tests to pass, but I cannot get that so show up online.
The code is showing the learn submit command not working.

I think the problem has to do with the fact that I accidentally edited the .rspec file

Also, the Ask A Question button does not work.
OSX El Capitan - Google Chrome

**Comment by AnnJohn** [comment]
hi @rhoprhh this looks like a technical bug so could you please file a bug report. If you hover over your profile pic in Learn, you'll see an option to report a bug. Thanks!
